[package]
name = "tstool"
version = "0.1.0"
authors = ["Norbert Melzer <timmelzer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.10.0"
clap = "^2.33"
serde = "^1.0"
serde_derive = "^1.0"
